### PR TITLE
bump devenv-nixpkgs

### PR DESCRIPTION
**Pull request by k3yss**
This PR bumps `devenv-nixpkgs` to https://github.com/NixOS/nixpkgs/commit/b9014df496d5 while applying all the patches that were present in `devenv-nixpkgs`

cc @domenkozar

### CODE REVIEW

**Comment by domenkozar** [comment]
The issue is that we need to bring back Python patch that allows us to fix virtualenv.

**Comment by k3yss** [comment]
@domenkozar  Can you link me the commit hash of those commits, I can cherry-pick those on top of this PR.

**Comment by domenkozar** [comment]
It's quite complicated to explain, I'll handle it.

**Comment by therealpxc** [comment]
> It's quite complicated to explain, I'll handle it.

I'm playing around trying to use a newer `uv` than is in this repo, which adds the command `uv sync`, which installs the dependencies specified in a `pyproject.toml` file to the project's venv. I'm running into problems and I've spent all night trying to get to the bottom of them.

I'd like to understand everything and anything special that devenv does with Python in relation to virtualenvs. Can I convince you to provide a little more information even though that sounds like a pain?

**Comment by therealpxc** [comment]
Is [this](https://github.com/NixOS/nixpkgs/pull/297628), or is it something else?

**Comment by domenkozar** [comment]
See #2 for explanation.

@therealpxc here's an example how to use newer uv: https://github.com/cachix/devenv/commit/7df6f2bc57c3d4793d3f96e791a09c0f5261c1ac

**Pull request closed without merging**
